pr:
  &pr {
    type: select,
    proxies:
      [Proxy, Manual-a, Manual-b, Manual-c, HongKong, TaiWan, Singapore, Japan, America, Korea, DIRECT]}
pro:
  &pro {
    type: select,
    proxies:
      [Manual-a, Manual-b, Manual-c, HongKong, TaiWan, Singapore, Japan, America, Korea, DIRECT]}
###############################################订阅################################################# 
# --------------------------------------------------
use: &use
#   如果不希望自动切换请将下面两行注释对调
  type: select
#   type: url-test
  use:
    - YTOO
    # - 一元机场`
    # - 本地配置
use01: &use01
#   如果不希望自动切换请将下面两行注释对调
  type: select
#   type: url-test
  use:
    - YTOO
    - 一元机场
    # - 本地配置
proxy-providers:
  YTOO:
    type: http
    url: "https://api.oxycontinin.com/osubscribe.php?sid=58244&token=7hKnEBWWAPXx3mtZRYEA"
    interval: 3600
    path: ./proxy_provider/YTOO.yaml
    header:
      User-Agent:
      - "clash.meta"
      - "mihomo/1.18.3"
    health-check:
      enable: false
      interval: 600
      url: https://cp.cloudflare.com/generate_204
    override: # 覆写节点加载时的一些配置项
      skip-cert-verify: true
      udp: true
  一元机场:
    type: http
    url: "https://xn--cp3a08l.com/api/v1/client/subscribe?token=59d4dc0290320b44c5fd9201b0bc8be7"
    interval: 3600
    path: ./proxy_provider/一元机场.yaml
    proxy: DIRECT
    header:
      User-Agent:
      - "clash.meta"
      - "mihomo/1.18.3"

    health-check:
      enable: false
      interval: 600
      url: https://cp.cloudflare.com/generate_204
    override: # 覆写节点加载时的一些配置项
      skip-cert-verify: true
      udp: true
###########################################常规设置#################################################
port: 7890
socks-port: 7891
mixed-port: 7893
redir-port: 7892
tproxy-port: 7895
allow-lan: true
bind-address: "*"
mode: rule
tcp-concurrent: true
unified-delay: true
geox-url:
  mmdb: https://testingcf.jsdelivr.net/gh/alecthw/mmdb_china_ip_list@release/Country.mmdb
  geoip: https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  asn: https://testingcf.jsdelivr.net/gh/xishang0128/geoip@release/GeoLite2-ASN.mmdb
geo-auto-update: true # 是否自动更新 geodata
geo-update-interval: 24 # 更新间隔，单位：小时
geodata-mode: true
log-level: info
ipv6: true
external-controller: 0.0.0.0:9090
profile:
  store-selected: true
  store-fake-ip: true
tun:
  enable: true
  stack: system
  dns-hijack:
    - 0.0.0.0:53
  auto-detect-interface: false
  auto-route: false
  auto-redirect: false
  strict-route: false
  endpoint-independent-nat: true
sniffer:
  enable: true
  override-destination: true
  sniff:
    QUIC:
      ports:
      - 443
    TLS:
      ports:
      - 443
      - 8443
    HTTP:
      ports:
      - 80
      - 8080-8880
      override-destination: true
  force-domain:
    - "+.netflix.com"
    - "+.nflxvideo.net"
    - "+.amazonaws.com"
    - "+.media.dssott.com"
  skip-domain:
    - "+.apple.com"
    - Mijia Cloud
    - dlg.io.mi.com
    - "+.oray.com"
    - "+.sunlogin.net"
    - "+.push.apple.com"
  parse-pure-ip: true
  force-dns-mapping: true

dns:
  enable: true
  listen: 0.0.0.0:7874
  ipv6: true
  default-nameserver:
    - 114.114.114.114
    - tls://223.5.5.5:853
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - geosite:cn
  fake-ip-filter-mode: blacklist
  respect-rules: false
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
###################################################代理组######################################################
proxy-groups:
  - { name: Final, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png, <<: *pr }
  - { name: Proxy, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png, <<: *pro}
  - { name: Manual-a, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Rocket.png, <<: *use01}
  - { name: Manual-b, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Rocket.png, <<: *use01, filter: "(?i)印尼|下载使用|美国洛杉矶|俄|俄罗斯|日用|香港 04|美国 09|美国 10" }
  - { name: Manual-c, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Rocket.png, <<: *use01, filter: "(?i)狮城|新加坡|美国|新|美" }
  - { name: LLM, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/ChatGPT.png, <<: *pr }
  - { name: YouTube, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png, <<: *pr }
  - { name: Spotify, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Spotify.png, <<: *pr }
  - { name: IM, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png, <<: *pr }
  - { name: SNS, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Instagram.png, <<: *pr }
  - { name: Apple, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple.png, <<: *pr }
  - { name: Google, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google.png, <<: *pr }
  - { name: Microsoft, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Microsoft.png, <<: *pr }
  - { name: Game, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Game.png, <<: *pr }
  - { name: Adblock, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/AdBlack.png, type: select, proxies: [REJECT, DIRECT, Proxy] }
  - { name: Mainland, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Direct.png, type: select, proxies: [DIRECT, Proxy] }
  # 分隔,下面是地区分组
  - { name: HongKong, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png, type: url-test, url: "https://cp.cloudflare.com/generate_204", interval: 300, tolerance: 50, use: [YTOO], filter: "(?i)港|hk|hongkong|hong kong" }
  - { name: TaiWan, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/China.png, type: url-test, url: "https://cp.cloudflare.com/generate_204", interval: 300, tolerance: 50, use: [YTOO], filter: "(?i)台|tw|taiwan" }
  - { name: Japan, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Japan.png, type: url-test, url: "https://cp.cloudflare.com/generate_204", interval: 300, tolerance: 50, use: [YTOO], filter: "(?i)日本|jp|japan" }
  - { name: America, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png, type: url-test, url: "https://cp.cloudflare.com/generate_204", interval: 300, tolerance: 50, use: [YTOO], filter: "(?i)美|us|unitedstates|united states" }
  - { name: Singapore, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Singapore.png, type: url-test, url: "https://cp.cloudflare.com/generate_204", interval: 300, tolerance: 50, use: [YTOO], filter: "(?i)新|狮|sg|singapore" }
  - { name: Korea, icon: https://gh-proxy.com/https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Korea.png, type: url-test, url: "https://cp.cloudflare.com/generate_204", interval: 300, tolerance: 50, use: [YTOO], filter: "(?i)KR|Korea|KOR|首尔|韩|韓" }
  
###################################################规则订阅#######################################################
rule-providers:
  AWAvenue-Ads:  # 秋风广告拦截规则
    type: http
    behavior: domain
    format: yaml
    # path: ./rule_provider/AWAvenue-Ads.yaml     # path可为空(仅限clash.meta 1.15.0以上版本)
    url: "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml"
    interval: 64800
  misaeng-direct:
    type: http
    behavior: classical
    format: text
    # path: ./rule_provider/AWAvenue-Ads.yaml     # path可为空(仅限clash.meta 1.15.0以上版本) 
    url: "https://raw.githubusercontent.com/songzhengpei/misaeng/refs/heads/main/direct0.txt"
    interval: 64800    
  misaeng-proxy:
    type: http
    behavior: classical
    format: text
    # path: ./rule_provider/AWAvenue-Ads.yaml    # path可为空(仅限clash.meta 1.15.0以上版本)
    url: "https://raw.githubusercontent.com/songzhengpei/misaeng/refs/heads/main/proxy.txt"
    interval: 64800    
  misaeng-llm:
    type: http
    behavior: classical
    format: text
    # path: ./rule_provider/AWAvenue-Ads.yaml       # path可为空(仅限clash.meta 1.15.0以上版本)
    url: "https://raw.githubusercontent.com/songzhengpei/misaeng/refs/heads/main/llm.txt"
    interval: 64800    
  ai-domain:
    type: http
    behavior: classical
    format: text
    # path: ./rule_provider/AWAvenue-Ads.yaml       # path可为空(仅限clash.meta 1.15.0以上版本)
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/category-ai-!cn.list"
    interval: 64800    
  testflight:
    type: http
    behavior: classical
    format: text
    # path: ./rule_provider/AWAvenue-Ads.yaml    # path可为空(仅限clash.meta 1.15.0以上版本)
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TestFlight/TestFlight.list"
    interval: 64800    
  game-download-cdn:
    type: http
    behavior: classical
    format: text
    # path: ./rule_provider/AWAvenue-Ads.yaml     # path可为空(仅限clash.meta 1.15.0以上版本)
    url: "https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/refs/heads/main/rule/Game_Download_CDN.list"
    interval: 64800    
  steam-cdn:
    type: http
    behavior: classical
    format: text
    # path: ./rule_provider/AWAvenue-Ads.yaml    # path可为空(仅限clash.meta 1.15.0以上版本)
    url: "https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/refs/heads/main/rule/Steam_CDN.list"
    interval: 64800    
####################################################规则顺序##################################################
rules:
# 前置规则
# - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOSITE,cn))),REJECT # quic
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.metacubex.one,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN,d.metacubex.one,DIRECT
  - DOMAIN,board.zash.run.place,DIRECT
  - RULE-SET,AWAvenue-Ads,Adblock
  - RULE-SET,misaeng-direct,Mainland
  - RULE-SET,misaeng-proxy,Proxy
  - RULE-SET,misaeng-llm,LLM
  - GEOSITE,category-public-tracker,Mainland
# 应用规则
  - GEOSITE,github,Proxy
  - GEOSITE,speedtest,Proxy
  - RULE-SET,testflight,Proxy
  - GEOSITE,category-ai-!cn,LLM
  - GEOSITE,youtube,YouTube
  - GEOSITE,category-communication,IM
  - GEOSITE,category-social-media-!cn,SNS
  - GEOIP,google,Google,no-resolve
  - GEOIP,telegram,IM,no-resolve
  - GEOIP,twitter,SNS,no-resolve
  - GEOIP,facebook,SNS,no-resolve
  - GEOSITE,spotify,Spotify
  - GEOSITE,apple,Apple
  - GEOSITE,google-cn,Google # Google CN 不走代理会导致香港等地区节点 Play Store 异常
  - GEOSITE,google,Google
  - GEOSITE,onedrive,Microsoft
  - GEOSITE,microsoft,Microsoft
  - GEOSITE,category-game-platforms-download,Mainland
  - RULE-SET,game-download-cdn,Mainland
  - RULE-SET,steam-cdn,Mainland
  - GEOSITE,steam@cn,Mainland
  - GEOSITE,steam,Game
  - GEOSITE,category-games@cn,Mainland
  - GEOSITE,category-games,Game
  - GEOSITE,geolocation-!cn,Proxy
#  后置规则
# - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOIP,CN))),REJECT # quic
  - GEOIP,private,Mainland,no-resolve
  - GEOSITE,CN,Mainland
  - GEOIP,CN,Mainland,no-resolve
#  绕过局域网地址
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - MATCH,Final
